# Loading in DataFrames from Files

In [2]:
import pandas as pd
import fastparquet
import openpyxl

In [3]:
# coffee = pd.read_csv('./warmup-data/coffee.csv' skipinitialspace=True)      # Used to skip if there are initial spaces in the dataset.
# coffee = pd.read_csv('./warmup-data/coffee.csv' skip_blank_lines=True)      # Used to skip if there are blank lines in the dataset.
coffee = pd.read_csv('./warmup-data/coffee.csv')

coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [4]:
results = pd.read_parquet('./data/results.parquet')         # we must import 'fastparquet' to read this file.
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

In [5]:
# olympics_data = pd.read_excel('./data/olympics-data.xlsx')            # We need to import 'openpyxl' to read this file.
olympics_data = pd.read_excel('./data/olympics-data.xlsx', sheet_name='results')
olympics_data.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [6]:
bios_data = pd.read_csv('./data/bios.csv')
# bios_data.to_csv()
# bios_data.to_parquet()
# bios_data.to_excel()

# Accessing Data with Pandas

In [7]:
coffee.sample(10)       # This will give 10 random data item's.
# coffee.sample(10, random_state=1)

          Day Coffee Type  Units Sold
9      Friday       Latte          35
1      Monday       Latte          15
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
12     Sunday    Espresso          45
0      Monday    Espresso          25
8      Friday    Espresso          45
6    Thursday    Espresso          40
11   Saturday       Latte          35
13     Sunday       Latte          35

### Accessing Specific values using .loc and .iloc

In [8]:
# Format of using .loc => coffee.loc[row, column]

# coffee.loc[0]
# coffee.loc[[0,1,2]]
# coffee.loc[[0,1,5]]
# coffee.loc[0:3]
# coffee.loc[0:]
# coffee.loc[5:]
# coffee.loc[5:8]

# coffee.loc[5:8, ["Day"]]        # Used to only fetch the 'Day' column.
coffee.loc[:, ["Day", "Units Sold"]]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [9]:
# Format of using .iloc => coffee.iloc[row, column(in index format)]

coffee.iloc[:13, [0,2]]             # It is almost same as .loc but the difference is that the upper index is excluded in .iloc and included in .loc

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45

### Modification in DataFrame using .loc and .iloc

In [10]:
coffee.iloc[1, 2] = 10      # Changed the value of first row and second column (indexwise) from 15 to 10.
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          10
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

### Accessing specific single value using .at and .iat

In [11]:
# Format of using .at => coffee.at[row, column]

coffee.at[0, "Day"]

'Monday'

In [12]:
# Format of using .iat => coffee.iat[row, column(in index format)]

# coffee.iat[0, 2]
# str(coffee.iat[0, 2])
coffee.iat[0, 1]

'Espresso'

### Sorting of DataFrame

In [13]:
# coffee.sort_values("Day")
# coffee.sort_values("Day", ascending=False)
coffee.sort_values(["Day", "Units Sold"], ascending=[0,1])      # This line states that sort values axxording to 'Day' and 'Units Sold' and keep ascending 'False' for 'Day' and 'True' for 'Units Sold'

          Day Coffee Type  Units Sold
5   Wednesday       Latte          25
4   Wednesday    Espresso          35
3     Tuesday       Latte          20
2     Tuesday    Espresso          30
7    Thursday       Latte          30
6    Thursday    Espresso          40
13     Sunday       Latte          35
12     Sunday    Espresso          45
11   Saturday       Latte          35
10   Saturday    Espresso          45
1      Monday       Latte          10
0      Monday    Espresso          25
9      Friday       Latte          35
8      Friday    Espresso          45

In [14]:
# This is another way of sorting but it has some disadvantages like -> more memory usage, low performance compared to NumPY functions.

for index, row in coffee.iterrows():
    print(index)
    print(row["Day"])
    print(row["Units Sold"])
    print("\n\n")

0
Monday
25



1
Monday
10



2
Tuesday
30



3
Tuesday
20



4
Wednesday
35



5
Wednesday
25



6
Thursday
40



7
Thursday
30



8
Friday
45



9
Friday
35



10
Saturday
45



11
Saturday
35



12
Sunday
45



13
Sunday
35

### Filtering Data

In [15]:
# bios_data.info()
# bios_data.loc[bios_data["height_cm"] > 215]
bios_data.loc[bios_data["height_cm"] > 215, ["name", "height_cm"]]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [16]:
# Short-Hand method to write the above code.
bios_data[bios_data["height_cm"] > 215] [['name', 'height_cm']]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [17]:
# When we have multiple condtitons to apply.
bios_data[(bios_data["height_cm"] > 215) & (bios_data["born_country"] == "USA")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN