# Loading in DataFrames from Files

In [6]:
import pandas as pd
import fastparquet
import openpyxl

In [5]:
coffee = pd.read_csv('./warmup-data/coffee.csv')

coffee.head()

         Day  Coffee Type   Units Sold
0     Monday     Espresso           25
1     Monday        Latte           15
2    Tuesday     Espresso           30
3    Tuesday        Latte           20
4  Wednesday     Espresso           35

In [ ]:
results = pd.read_parquet('./data/results.parquet')
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

In [8]:
# olympics_data = pd.read_excel('./data/olympics-data.xlsx')
olympics_data = pd.read_excel('./data/olympics-data.xlsx', sheet_name='results')
olympics_data.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [9]:
bios_data = pd.read_csv('./data/bios.csv')
# bios_data.to_csv()
# bios_data.to_parquet()
# bios_data.to_excel()

# Accessing Data with Pandas